# Generated by Django 5.1.7 on 2025-04-15 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_admin', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_admin.clients'),
        ),
    ]
