# Generated by Django 5.2 on 2025-04-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL para eliminar la restricción existente
            "ALTER TABLE market_order DROP FOREIGN KEY market_order_usuario_id_bcdda766_fk_account_admin_clients_id;",
            # SQL para revertir (rollback)
            "ALTER TABLE market_order ADD CONSTRAINT market_order_usuario_id_bcdda766_fk_account_admin_clients_id FOREIGN KEY (usuario_id) REFERENCES account_admin_clients(id);"
        ),
        migrations.RunSQL(
            # SQL para añadir la nueva restricción que apunta a la tabla de usuarios correcta
            "ALTER TABLE market_order ADD CONSTRAINT market_order_usuario_id_fk FOREIGN KEY (usuario_id) REFERENCES account_admin_user(id);",
            # SQL para revertir
            "ALTER TABLE market_order DROP FOREIGN KEY market_order_usuario_id_fk;"
        ),
    ]
