# Generated by Django 5.2 on 2025-04-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_fix_order_usuario_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='fecha_entrega_estimada',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
