# Generated by Django 5.1.7 on 2025-04-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_envio_numero_guia_pago_monto_pagado_pedido_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='Anonimo', max_length=100, unique=True),
        ),
    ]
