# Generated by Django 5.1.7 on 2025-04-10 21:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_cliente_usuario_cliente_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='DetallePedido',
            new_name='OrderDetail',
        ),
        migrations.RenameModel(
            old_name='Pago',
            new_name='Pay',
        ),
        migrations.RenameModel(
            old_name='Producto',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Envio',
            new_name='Shipment',
        ),
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='Supplier',
        ),
    ]
